.card{
  /* font-size: calc(15px + 0.390625vw); */

}

.cardImage {
	display: block;
	width: 100%; 
}

.title {
	margin: 0;
	font-size: 1.4rem;
}

@media (min-width: 50em) {
	.title {
		font-size: 1.8rem;
	}
}

.card {
	--shadowColor: 49 92% 67%; 
	display: flex;
	flex-wrap: wrap;
	background: #f8dc5f2c;
	max-width: 500px;
	width: 100%;
	box-shadow: 0.65rem 0.65rem 0 hsl(var(--shadowColor) / 1);
	border-radius: 0.8rem;
	overflow: hidden;
	border: 0.4rem solid;
}

.cardImage {
	aspect-ratio: 3 / 2;
	object-fit: cover;
	/* object-fit: contain; */
	flex: 1 1 150px;
	outline: 0.4rem solid;
  height: 150px;
  height: 100%;
}

.textColumn {
	padding: min(2rem, 5vw) min(2rem, 5vw) min(2.5rem, 5vw);
	flex: 1 0 50%;
}

.description {
  margin: 3rem;
  
}

.textColumn > * + * {
	margin: min(.5rem, 2.5vw) 0 0 0;
}

.card a  {
	display: inline-block;
	color: black;
	padding: 0.5rem 1rem;
	text-decoration: none;
	background: hsl(187 75% 64%);
	background: #F8DB5F;

  
	border-radius: 0.6rem;
	font-weight: 700;
	border: 0.25rem solid;
  
}